---
kind: GatewayClass
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: blixt-tcproute-sample
  namespace: gwapi-ref-ns
spec:
  controllerName: konghq.com/blixt
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: blixt-tcproute-sample
  namespace: gwapi-ref-ns
spec:
  gatewayClassName: blixt-tcproute-sample
  listeners:
  - name: tcp
    protocol: TCP
    port: 8080
