apiVersion: bpfd.dev/v1alpha1
kind: TcProgram
metadata:
  labels:
    app.kubernetes.io/name: blixt-tc-egress
  name: tc-egress
spec:
  bpffunctionname: tc_egress
  # Select all nodes
  nodeselector: {}
  interfaceselector:
    primarynodeinterface: true
  priority: 0
  direction: egress
  bytecode:
    image:
      url: quay.io/bpfd-bytecode/blixt-tc-egress:latest
      imagepullpolicy: Always
  mapownerselector:
    matchLabels:
      bpfd.dev/ownedByProgram: blixt-tc-ingress
