apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
## bpfd CRDs
- https://github.com/bpfd-dev/bpfd/releases/download/v0.3.0/bpfd-crds-install-v0.3.0.yaml
## bpfd Operator
- https://github.com/bpfd-dev/bpfd/releases/download/v0.3.0/bpfd-operator-install-v0.3.0.yaml

patches:
- path: patch.yaml
  target:
    kind: ConfigMap
    name: config
    version: v1
    name: bpfd-config
